# Site settings
title: Mis Mascotas
description: las mascotas man traviesos
keywords: Mascotas
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
